version: "3.2"
services:

  mysql:
    image: mysql:latest
    container_name: 'app-mysql'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: eventify
      MYSQL_USER: eventify
  rabbitmq:
    build:
      context: .
      dockerfile: ./src/docker/rabbitmq/Dockerfile
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    environment:
      RABBITMQ_DELAYED_MESSAGE_EXCHANGE: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./src/docker/app/Dockerfile.dev
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_started
    ports:
      - 3000:3000
    container_name: 'app'
    volumes:
      - .:/usr/dev
  nginx:
      image: nginx:latest
      container_name: 'my-nginx'
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app

volumes:
  mysql:
    driver: local